import "./globals.css";
import { ToastContainer } from "react-toastify";
import { GoogleOAuthProvider } from "@react-oauth/google";
import dotenv from "dotenv";
import { ChatProvider } from "@/hooks/useChat";

dotenv.config();

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <GoogleOAuthProvider clientId="826677420756-nko3kgf62n3sr85l5spgduhs1qi2o0tq.apps.googleusercontent.com">
      <html lang="en">
        <body className={` antialiased`} suppressHydrationWarning>
          <ChatProvider>
            <ToastContainer />
            {children}
          </ChatProvider>
        </body>
      </html>
    </GoogleOAuthProvider>
  );
}
