import "./globals.css";
import { ToastContainer } from "react-toastify";
import { GoogleOAuthProvider } from "@react-oauth/google";
import dotenv from "dotenv";
import { ChatProvider } from "@/hooks/useChat";

dotenv.config();


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={` antialiased`}
        suppressHydrationWarning
      >
        <ChatProvider>

        <ToastContainer />
        </ChatProvider>
        {children}
      </body>
    </html>
  );
}
